name = "novel-worldbuilding-chatbot"
main = "src/worker/index.ts"
compatibility_date = "2026-05-13"
workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "novel_worldbuilding_chatbot"
database_id = "2219b7ec-d85a-4c6b-9c72-c7b80ebcefb1"
migrations_dir = "./migrations"
